// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SaveToSheets(arg1) {
  return window['go']['main']['App']['SaveToSheets'](arg1);
}

export function SelectImage() {
  return window['go']['main']['App']['SelectImage']();
}
