// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function SaveToSheets(arg1:main.ProductData):Promise<string>;

export function SelectImage():Promise<string>;
